### ISSUE TITLE
onConnectionFailed() method is being called

### ISSUE THREAD

**Issue by nabinkhadka** [seanpjanson/GDAADemo#1]
I just downloaded this, then imported. I enabled OAuth from console.developers.google.com according to my package name. But each time I run this code, I get onConnectionFailed() method is being called and hence the activity gets closed.

What is wrong here?

**Comment by nabinkhadka** [comment]
OK! I solved it :-) Just changed the email address to mine at Consent Screen of console.developers.google.com.

**Comment by seanpjanson** [comment]
@nabinkhadka Please, can you elaborate what happened? I'd like to add it to the README for others, if it is relevant. Thanks, Sean

**Comment by nabinkhadka** [comment]
Is it possible to use it in Adapter class?

**Comment by nabinkhadka** [comment]
@seanpjanson I just messed up in google console. Inside the consent screen, I forgot to choose my email address. That's it. Thank you

**Comment by seanpjanson** [comment]
README.MD - last sentence

**Comment by nabinkhadka** [comment]
Is the link correct?
